const { Client } = require("../../models");

const clients = [
  {
    mail: "alejandraoviedodeo1lmos@gmail.com",
    telefono: 1136174061,
    datos_del_grupo:
      "Un grupo de Adult@s mayores muy interesados por la Historia",
    institucion: "Escuela Primaria N°79 Río De La Plata",
    direccion: "Marinero Lopez 565",
    provincia: "Provincia de Buenos Aires",
    localidad: "Quilmes",
    gestion: "Pública",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 6,
    requerimientos_especificos: "No",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "septimo",
    actividad_solicitada: "septimo",
    shiftId: 1,
    activityId: 1,
  },
  {
    mail: "brunomosernune2s@hotmail.com",
    telefono: 1562745147,
    datos_del_grupo:
      "Un grupo de Adult@s mayores muy interesados por la Historia",
    institucion: "Universidad de Adultos mayores de Morón",
    direccion: "Arrecifes 974 Castelar",
    provincia: "Provincia de Buenos Aires",
    localidad: "Morón",
    gestion: "Pública",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 1,
    requerimientos_especificos: "No.",
    autoriza_foto: true,
    grupo: "Adultes Mayores",
    tipo_de_curso: "universidad",
    actividad_solicitada: "universidad",
    shiftId: 2,
    activityId: 2,
  },
  {
    mail: "marisa.c3asares@bue.edu.ar",
    telefono: 1157404136,
    datos_del_grupo:
      "Un grupo de Adult@s mayores muy interesados por la Historia",
    institucion: "ET N 32  Gral Jose de San Martín ",
    direccion: "Teodoro García 3899",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Chacarita ",
    gestion: "Pública",
    cantidad_de_personas: 32,
    cantidad_de_docentes: 2,
    requerimientos_especificos: "No",
    autoriza_foto: true,
    grupo: "Secundario",
    tipo_de_curso: "tercero",
    actividad_solicitada: "tercero",
    shiftId: 3,
    activityId: 3,
  },
  {
    mail: "carolinaele4norarossi55@gmail.com",
    telefono: 541137819169,
    datos_del_grupo:
      "Un grupo de Adult@s mayores muy interesados por la Historia",
    institucion: "Colegio argentino arabe ",
    direccion: "Humberto primo 3050",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Boedo",
    gestion: "Privada",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 3,
    requerimientos_especificos: "Si. Son estudiantes sordos hablantes de LSA",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 4,
    activityId: 4,
  },
  {
    mail: "englishde5partment@abrown.com.ar",
    telefono: "0230154370704",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Colegio a A Brown",
    direccion: "Sanguinetti 1210 Pilar",
    provincia: "Provincia de Buenos Aires",
    localidad: "Pilar",
    gestion: "Privada",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 3,
    requerimientos_especificos: "no",
    autoriza_foto: true,
    grupo: "Secundario",
    tipo_de_curso: "tercero ",
    actividad_solicitada: "tercero ",
    shiftId: 5,
    activityId: 5,
  },
  {
    mail: "5gradosabri2023@gmail.com6",
    telefono: "1159332168",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Colegio Del Carmen",
    direccion: "Paraguay 1766",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Recoleta",
    gestion: "Privada",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 2,
    requerimientos_especificos: "no",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 6,
    activityId: 6,
  },
  {
    mail: "anabella.frankel@dbosco.edu.ar",
    telefono: "1521602346",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Colegio Don Bosco",
    direccion: "Solis 252",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Balvanera",
    gestion: "Privada",
    cantidad_de_personas: 34,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "no",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 7,
    activityId: 7,
  },
  {
    mail: "escuela19biblioteca@gmail.com",
    telefono: "1521602346",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Colegio Don Bosco",
    direccion: "Solis 252",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Balvanera",
    gestion: "Privada",
    cantidad_de_personas: 34,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "Alumna con inclusión que tiene acompañante",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 8,
    activityId: 8,
  },
  {
    mail: "gabividal2015@gmail.com",
    telefono: "1137872477",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Escuela primaria N°19 ROMA D.E. 20",
    direccion: "Cosquín 3100",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Mataderos",
    gestion: "Pública",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "no",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 9,
    activityId: 9,
  },
  {
    mail: "nadiaortiz.efedi@gmail.com",
    telefono: "1137872477",
    datos_del_grupo: "Curioso, SALA DE 5 AÑOS",
    institucion: "Escuela primario N°19 ROMA D.E. 20",
    direccion: "Cosquín 3100",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Mataderos",
    gestion: "Pública",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "No",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 10,
    activityId: 10,
  },
  {
    mail: "sabrina.regert@bue.edu.ar",
    telefono: "1540519817",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Efedi",
    direccion: "Av La Plata 1707",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Parque Chacabuco",
    gestion: "Privada",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 6,
    requerimientos_especificos: "No",
    autoriza_foto: true,
    grupo: "Primario (2° a 4° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 11,
    activityId: 11,
  },
  {
    mail: "isisguzman.m@gmail.com",
    telefono: "1160238339",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Efedi",
    direccion: "Av. La Plata 1707",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Parque Chacabuco ",
    gestion: "Privada",
    cantidad_de_personas: 35,
    cantidad_de_docentes: 5,
    requerimientos_especificos: "No",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 12,
    activityId: 12,
  },
  {
    mail: "noelia.santa@bue.edu.ar",
    telefono: "1136808012",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Almirante Guillermo Brown ",
    direccion: "Aristóbulo del Valle 471",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Barracas ",
    gestion: "Pública",
    cantidad_de_personas: 20,
    cantidad_de_docentes: 2,
    requerimientos_especificos: "Ninguna",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 13,
    activityId: 13,
  },
  {
    mail: "santacruz.noelia@gmail.com",
    telefono: "01138268890",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "San Vicente de Paul ",
    direccion: "Manuel Artigas 6142",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Mataderos ",
    gestion: "Privada",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "No",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 14,
    activityId: 14,
  },
  {
    mail: "andrea.larocca@bue.edu.ar",
    telefono: "1131034153",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela N° 21 D.E 4",
    direccion: "Perú 946",
    provincia: "Ciudad de Buenos Aires",
    localidad: "San Telmo",
    gestion: "Pública",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "no",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 15,
    activityId: 15,
  },
  {
    mail: "profegudaitis@gmail.com",
    telefono: "1131034153",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela n° 21 D.E.4°",
    direccion: "Perú 946",
    provincia: "Ciudad de Buenos Aires",
    localidad: "San Telmo",
    gestion: "Pública",
    cantidad_de_personas: 30,
    cantidad_de_docentes: 4,
    requerimientos_especificos: "no",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 16,
    activityId: 16,
  },
  {
    mail: "maria.pedemonte@bue.edu.ar",
    telefono: "01159116287",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela N° 2 DE 8",
    direccion: "Santander 1150",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Parque Chcabuco",
    gestion: "Pública",
    cantidad_de_personas: 23,
    cantidad_de_docentes: 2,
    requerimientos_especificos: "Alumno chino",
    autoriza_foto: false,
    grupo: "Primario (2° a 4° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 17,
    activityId: 17,
  },
  {
    mail: "profegudaiti7s@gmail.com",
    telefono: "01159116287",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela N° 2 DE 8",
    direccion: "Santander 1150",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Parque Chcabuco",
    gestion: "Pública",
    cantidad_de_personas: 23,
    cantidad_de_docentes: 2,
    requerimientos_especificos: "no",
    autoriza_foto: false,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 18,
    activityId: 1,
  },
  {
    mail: "profegudait8is@gmail.com",
    telefono: "01159645141",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela de Cerámica n1 ",
    direccion: "Bulnes 45",
    provincia: "Ciudad de Buenos Aires",
    localidad: "Palermo",
    gestion: "Pública",
    cantidad_de_personas: 32,
    cantidad_de_docentes: 3,
    requerimientos_especificos: "Si",
    autoriza_foto: true,
    grupo: "Secundario",
    tipo_de_curso: "tercero",
    actividad_solicitada: "tercero",
    shiftId: 19,
    activityId: 2,
  },
  {
    mail: "prof5464egudaitis@gmail.com",
    telefono: "1159351600",
    datos_del_grupo:
      "Son un grupo de estudiantes de entre 15 y 60 años, algunos terminando su escuela primaria y otros en etapa de alfabetización ",
    institucion: "Escuela 2 de 8",
    direccion: "Santander 1150",
    provincia: "Ciudad de Buenos Aires",
    localidad: "CABA",
    gestion: "Pública",
    cantidad_de_personas: 21,
    cantidad_de_docentes: 3,
    requerimientos_especificos: "no",
    autoriza_foto: true,
    grupo: "Primario (5° a 7° grado)",
    tipo_de_curso: "quinto",
    actividad_solicitada: "quinto",
    shiftId: 20,
    activityId: 3,
  },
];

async function createClients() {
  try {
    await Client.bulkCreate(clients);
    console.log("CLIENTS created Ok");
  } catch (error) {
    console.log(error);
  }
}

module.exports = createClients;
